// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.wavemaker.poc.grpc.model;

public interface EchoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpctest.EchoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
