// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.wavemaker.poc.grpc.model;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpctest.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string firstname = 2;</code>
   * @return The firstname.
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 2;</code>
   * @return The bytes for firstname.
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string lastname = 3;</code>
   * @return The lastname.
   */
  java.lang.String getLastname();
  /**
   * <code>string lastname = 3;</code>
   * @return The bytes for lastname.
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>string locations = 4;</code>
   * @return The locations.
   */
  java.lang.String getLocations();
  /**
   * <code>string locations = 4;</code>
   * @return The bytes for locations.
   */
  com.google.protobuf.ByteString
      getLocationsBytes();

  /**
   * <code>bool active = 5;</code>
   * @return The active.
   */
  boolean getActive();
}
