// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.wavemaker.poc.grpc.model;

public final class EmployeeServiceProto {
  private EmployeeServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpctest_EchoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpctest_EchoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpctest_EchoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpctest_EchoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpctest_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpctest_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeService.proto\022\010grpctest\032\033googl" +
      "e/protobuf/empty.proto\032\036google/protobuf/" +
      "wrappers.proto\"2\n\013EchoRequest\022\021\n\tfirstNa" +
      "me\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\" \n\014EchoRespon" +
      "se\022\020\n\010greeting\030\001 \001(\t\"^\n\010Employee\022\n\n\002id\030\001" +
      " \001(\t\022\021\n\tfirstname\030\002 \001(\t\022\020\n\010lastname\030\003 \001(" +
      "\t\022\021\n\tlocations\030\004 \001(\t\022\016\n\006active\030\005 \001(\0102\233\003\n" +
      "\017EmployeeService\022?\n\013addEmployee\022\022.grpcte" +
      "st.Employee\032\034.google.protobuf.StringValu" +
      "e\022?\n\013getEmployee\022\034.google.protobuf.Strin" +
      "gValue\032\022.grpctest.Employee\022B\n\014addEmploye" +
      "es\022\022.grpctest.Employee\032\034.google.protobuf" +
      ".StringValue(\001\022<\n\014getEmployees\022\026.google." +
      "protobuf.Empty\032\022.grpctest.Employee0\001\022J\n\022" +
      "getEmployeesStream\022\034.google.protobuf.Str" +
      "ingValue\032\022.grpctest.Employee(\0010\001\0228\n\004test" +
      "\022\034.google.protobuf.StringValue\032\022.grpctes" +
      "t.EmployeeB6\n\034com.wavemaker.poc.grpc.mod" +
      "elB\024EmployeeServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_grpctest_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpctest_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpctest_EchoRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_grpctest_EchoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpctest_EchoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpctest_EchoResponse_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_grpctest_Employee_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpctest_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpctest_Employee_descriptor,
        new java.lang.String[] { "Id", "Firstname", "Lastname", "Locations", "Active", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
